<?php

namespace Database\Seeders;

use App\Models\Report;
use Illuminate\Database\Seeder;

class ReportSeeder extends Seeder
{
    
    public function run(): void
    {
        Report::insert([
            //Bekalan Air
            ['name' => 'PAIP BEKALAN AIR PECAH', 'report_type_id' => 1],
            ['name' => 'PAIP BEKALAN BOCOR', 'report_type_id' => 1],
            ['name' => 'TANGKI AIR MELIMPAH', 'report_type_id' => 1],
            ['name' => 'TIADA BEKALAN AIR SATU BANGUNAN', 'report_type_id' => 1],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN BEKALAN AIR', 'report_type_id' => 1],
            //Lif
            ['name' => 'BUTTON LIF ROSAK', 'report_type_id' => 2],
            ['name' => 'KIPAS LIF TIDAK BERFUNGSI', 'report_type_id' => 2],
            ['name' => 'LIF TIDAK BERFUNGSI', 'report_type_id' => 2],
            ['name' => 'LIF TERGENDALA/PENUMPANG TERPERANGKAP', 'report_type_id' => 2],
            ['name' => 'LAMPU LIF TIDAK MENYALA', 'report_type_id' => 2],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN LIF', 'report_type_id' => 2],
            //Pencegah Kebakaran
            ['name' => 'TANGKI ARI PENCEGAH KEBAKARAN (MERAH) BOCOR/OVERFLOW', 'report_type_id' => 3],
            ['name' => 'PILI BOMBA BOCOR ', 'report_type_id' => 3],
            ['name' => 'LOCENG KECEMASAN PENCEGAH KEBAKARAN BERBUNYI', 'report_type_id' => 3],
            ['name' => 'PANEL PENGGERA KEBAKARAN TIADA BEKALAN KUASA', 'report_type_id' => 3],
            ['name' => 'KABINET PANEL PENGGERA KAWALAN ROSAK', 'report_type_id' => 3],
            ['name' => 'FUME DETECTOR', 'report_type_id' => 3],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN PENCEGAH KEBAKARAN', 'report_type_id' => 3],
            //Kerosakan Pintu
            ['name' => 'DOOR CLOSER ROSAK/TAK BERFUNGSI', 'report_type_id' => 4],
            ['name' => 'KUNCI PINTU ROSAK', 'report_type_id' => 4],
            ['name' => 'PINTU TERKUNCI', 'report_type_id' => 4],
            ['name' => 'SELAK PINTU ROSAK', 'report_type_id' => 4],
            ['name' => 'JENANG/BINGKAI PINTU ROSAK', 'report_type_id' => 4],
            ['name' => 'KUNCI/TOMBOL BERKARAT', 'report_type_id' => 4],
            ['name' => 'PINTU PECAH', 'report_type_id' => 4],
            ['name' => 'ANAK KUNCI PATAH', 'report_type_id' => 4],
            ['name' => 'HANDLE PINTU PATAH/ROSAK', 'report_type_id' => 4],
            ['name' => 'PINTU TERJATUH', 'report_type_id' => 4],
            ['name' => 'PINTU KETAT', 'report_type_id' => 4],
            ['name' => 'PINTU DIMAKAN ANAI-ANAI', 'report_type_id' => 4],
            ['name' => 'LAIN-LAIN KEROSAKAN PINTU', 'report_type_id' => 4],
            //Pemadam APi
            ['name' => 'HOSE REEL PEMADAM API ROSAK', 'report_type_id' => 5],
            ['name' => 'PEMADAM API TIDAK BERFUNGSI', 'report_type_id' => 5],
            ['name' => 'NOZZLE PEMADAM API PATAH', 'report_type_id' => 5],
            ['name' => 'KABINET HOSE REEL ROSAK', 'report_type_id' => 5],
            ['name' => 'PEMADAM API TAMAT TEMPOH', 'report_type_id' => 5],
            ['name' => 'GATE VALVE HOSE REEL PEMADAM API HILANG', 'report_type_id' => 5],
            ['name' => 'VALVE PEMANDAM API BOCOR', 'report_type_id' => 5],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN PEMADAM API', 'report_type_id' => 5],
            //Penyaman Udara
            ['name' => 'STARTER PENYAMAN UDARA ROSAK', 'report_type_id' => 6],
            ['name' => 'PENYAMAN UDARA TIDAK BERFUNGSI', 'report_type_id' => 6],
            ['name' => 'PENYAMAN UDARA TIDAK SEJUK', 'report_type_id' => 6],
            ['name' => 'AIR MENITIK DARI PENYAMAN UDARA', 'report_type_id' => 6],
            ['name' => 'PENYAMAN UDARA BERBAU BUSUK', 'report_type_id' => 6],
            ['name' => 'BUNYI BISING PADA PENYAMAN UDARA', 'report_type_id' => 6],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN PENYAMAN UDARA', 'report_type_id' => 6],
            //Mesin Perakam Waktu
            ['name' => 'MESIN PERAKAM TIDAK BERFUNGSI', 'report_type_id' => 7],
            ['name' => 'MASA PADA MESIN PERAKAM TIDAK TEPAT', 'report_type_id' => 7],
            ['name' => 'MELODI MESIN PERAKAM TIDAK BERFUNGSI', 'report_type_id' => 7],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN MESIN PERAKAM WAKTU', 'report_type_id' => 7],
            //Kebersihan Dalam Bangunan
            ['name' => 'TIADA TISU (TANDAS)', 'report_type_id' => 8],
            ['name' => 'TIADA SABUN (TANDAS)', 'report_type_id' => 8],
            ['name' => 'TANDAS KOTOR', 'report_type_id' => 8],
            ['name' => 'SILING/DINDING BERSAWANG', 'report_type_id' => 8],
            ['name' => 'LANTAI KOTOR', 'report_type_id' => 8],
            ['name' => 'PAPAN PUTIH TIDAK DIBERSIHKAN', 'report_type_id' => 8],
            ['name' => 'BANGUNAN KOTOR', 'report_type_id' => 8],
            ['name' => 'SAMPAH TIDAK DIPUNGUT', 'report_type_id' => 8],
            ['name' => 'PERABOT/PERALATAN BERHABUK', 'report_type_id' => 8],
            ['name' => 'KARPET BERBAU/KOTOR', 'report_type_id' => 8],
            ['name' => 'TANDAS BERBAU BUSUK', 'report_type_id' => 8],
            ['name' => 'BANGUNAN BERBAU', 'report_type_id' => 8],
            ['name' => 'LAIN-LAIN ADUAN KEBERSIHAN BANGUNAN', 'report_type_id' => 8],
            //Mesin Air Sejuk/Panas
            ['name' => 'PENAPIS BEKALAN MESIN AIR KOTOR', 'report_type_id' => 9],
            ['name' => 'MESIN AIR SEJUK/PANAS TAK BERFUNGSI', 'report_type_id' => 9],
            ['name' => 'FRONT COVER MESIN AIR SEJUK TERTANGGAL', 'report_type_id' => 9],
            ['name' => 'MESIN AIR SEJUK TERSUMBAT', 'report_type_id' => 9],
            ['name' => 'PAIP BEKALAN MESIN AIR SEJUK PATAH', 'report_type_id' => 9],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN MESIN AIR SEJUK', 'report_type_id' => 9],
            //Kerosakan Bangunan
            ['name' => 'SILING BERLUBANG', 'report_type_id' => 10],
            ['name' => 'SILING BOCOR', 'report_type_id' => 10],
            ['name' => 'SILING ROSAK/PECAH', 'report_type_id' => 10],
            ['name' => 'SILING RUNTUH', 'report_type_id' => 10],
            ['name' => 'SILING (KESAN RESAPAN AIR)', 'report_type_id' => 10],
            ['name' => 'SILING TIDAK DIPASANG', 'report_type_id' => 10],
            ['name' => 'CAT SILING KOTOR', 'report_type_id' => 10],
            ['name' => 'DINDING RETAK', 'report_type_id' => 10],
            ['name' => 'DINDING KOTOR/BERCONTENG', 'report_type_id' => 10],
            ['name' => 'LAMINAT DINDING ROSAK/MENGELUPAS', 'report_type_id' => 10],
            ['name' => 'BUMBUNG BOCOR', 'report_type_id' => 10],
            ['name' => 'BUMBUNG TERCABUT', 'report_type_id' => 10],
            ['name' => 'KAYU LANTAI PARKET DIMAKAN ANAI-ANAI', 'report_type_id' => 10],
            ['name' => 'LANTAI BERLUBANG/PECAH', 'report_type_id' => 10],
            ['name' => 'BLIND/LANGSIR ROSAK', 'report_type_id' => 10],
            ['name' => 'TINGKAP KETAT', 'report_type_id' => 10],
            ['name' => 'SELAK TUAS TINGKAP PATAH/ROSAK', 'report_type_id' => 10],
            ['name' => 'KACA TINGKAP PECAH', 'report_type_id' => 10],
            ['name' => 'BINGKAI TINGKAP REPUT', 'report_type_id' => 10],
            ['name' => 'JUBIN TERTANGGAL/TERKOPEK', 'report_type_id' => 10],
            ['name' => 'RAILING BESI TANGGA REPUT', 'report_type_id' => 10],
            ['name' => 'SIMEN SKRID TANGGA PECAH', 'report_type_id' => 10],
            ['name' => 'LAIN-LAIN KEROSAKAN BANGUNAN', 'report_type_id' => 10],
            //Peralatan Tandas dan Plumbing
            ['name' => 'TIADA BEKALAN AIR DI TANDAS', 'report_type_id' => 11],
            ['name' => 'KEPALA PAIP BOCOR', 'report_type_id' => 11],
            ['name' => 'KEPALA PAIP LONGGAR', 'report_type_id' => 11],
            ['name' => 'BASIN BASUH TANGAN BOCOR', 'report_type_id' => 11],
            ['name' => 'BASIN BASUH TANGAN PECAH', 'report_type_id' => 11],
            ['name' => 'BASIN BASUH TANGAN TERSUMBAT', 'report_type_id' => 11],
            ['name' => 'SALURAN TANDAS TERSUMBAT/TERSEKAT', 'report_type_id' => 11],
            ['name' => 'TANGKI PENYIMBAH PECAH', 'report_type_id' => 11],
            ['name' => 'BOTTLE TRAP ROSAK/BOCOR', 'report_type_id' => 11],
            ['name' => 'FLUSH VALVE ROSAK', 'report_type_id' => 11],
            ['name' => 'SHOWER HEAD ROSAK', 'report_type_id' => 11],
            ['name' => 'CERMIN TANDAS PECAH/ROSAK', 'report_type_id' => 11],
            ['name' => 'PAIP TANDAS BOCOR', 'report_type_id' => 11],
            ['name' => 'BESI PENYANGKUT PAKAIAN TERCABUT', 'report_type_id' => 11],
            ['name' => 'TANGKI TANDAS BOCOR/MELIMPAH', 'report_type_id' => 11],
            ['name' => 'FLUSHING HANDLE TAK BERFUNGSI/ROSAK', 'report_type_id' => 11],
            ['name' => 'PENDAKAP PAIP PATAH/TERCABUT', 'report_type_id' => 11],
            ['name' => 'MANGKUK TANDAS PECAH/ROSAK', 'report_type_id' => 11],
            ['name' => 'PELAPIK TANDAS DUDUK TIADA', 'report_type_id' => 11],
            ['name' => 'SALURAN PERANGKAP LANTAI TERSUMBAT', 'report_type_id' => 11],
            ['name' => 'LAIN-LAIN KEROSAKAN PERALATAN PLUMBING', 'report_type_id' => 11],
            //Sanitac Bin
            ['name' => 'SANITACT TIDAK TERURUS', 'report_type_id' => 12],
            ['name' => 'SANITACT TIDAK DIPUNGUT', 'report_type_id' => 12],
            ['name' => 'SANITACT BERBAU', 'report_type_id' => 12],
            ['name' => 'LAIN-LAIN ADUAN SANITARY BIN', 'report_type_id' => 12],
            //Lampu Dalam Bangunan
            ['name' => 'LAMPU MALAP', 'report_type_id' => 13],
            ['name' => 'LAMPU BERKELIP-KELIP', 'report_type_id' => 13],
            ['name' => 'LAMPU TIDAK MENYALA', 'report_type_id' => 13],
            ['name' => 'LAMPU TERTANGGAL', 'report_type_id' => 13],
            ['name' => 'LAMPU TIDAK DIPASANG', 'report_type_id' => 13],
            ['name' => 'LAMPU TANDA KELUAR (EXIT SIGN) ROSAK', 'report_type_id' => 13],
            ['name' => 'LAIN-LAIN ADUAN LAMPU DALAM BANGUNAN', 'report_type_id' => 13],
            //Lampu Luar Bangunan
            ['name' => 'TIANG LAMPU JALAN PATAH/BENGKOK', 'report_type_id' => 14],
            ['name' => 'LAMPU JALAN TIDAK BERNYALA', 'report_type_id' => 14],
            ['name' => 'LAIN-LAIN ADUAN LAMPU LUAR BANGUNAN', 'report_type_id' => 14],
            //Bekalan Elektrik
            ['name' => 'WAYAR/KABEL/TRUNKING TERBAKAR', 'report_type_id' => 15],
            ['name' => 'WAYAR/KABEL/TRUNKING ELEKTRIK TERJUNTAI', 'report_type_id' => 15],
            ['name' => 'WAYAR/KABEL/TRUNKING ELEKTRIK TERPUTUS', 'report_type_id' => 15],
            ['name' => 'BEKALAN ELEKTRIK TERPUTUS SATU BAHAGIAN', 'report_type_id' => 15],
            ['name' => 'BEKALAN ELEKTRIK TERPUTUS SATU ARAS', 'report_type_id' => 15],
            ['name' => 'BEKALAN ELEKTRIK TERPUTUS SATU BANGUNAN', 'report_type_id' => 15],
            ['name' => 'LAIN-LAIN ADUAN BEKALAN ELEKTRIK', 'report_type_id' => 15],
            //Pepasangan Elektrik
            ['name' => 'SOKET SUIS TERTANGGAL', 'report_type_id' => 16],
            ['name' => 'SOKET SUIS TERBAKAR', 'report_type_id' => 16],
            ['name' => 'SOKET SUIS TIADA BEKALAN', 'report_type_id' => 16],
            ['name' => 'SOKET SUIS PECAH', 'report_type_id' => 16],
            ['name' => 'SUIS TERTANGGAL', 'report_type_id' => 16],
            ['name' => 'SUIS PECAH', 'report_type_id' => 16],
            ['name' => 'PINTU PAPAN AGIHAN (DB) TERTANGGAL', 'report_type_id' => 16],
            ['name' => 'KOTAK PAPAN AGIHAN (DB) PECAH', 'report_type_id' => 16],
            ['name' => 'KIPAS ANGIN TERTANGGAL', 'report_type_id' => 16],
            ['name' => 'KIPAS ANGIN ROSAK', 'report_type_id' => 16],
            ['name' => 'LAIN-LAIN ADUAN PEPASANGAN ELEKTRIK', 'report_type_id' => 16],
            //Sistem Siaraya (PA System)
            ['name' => 'SISTEM SIARAYA (PA) ROSAK', 'report_type_id' => 17],
            ['name' => 'LAIN-LAIN KEROSAKAN SISTEM SIARAYA', 'report_type_id' => 17],
            //Sistem Audio Visual
            ['name' => 'SKRIN TAK BOLEH NAIK/TURUN', 'report_type_id' => 18],
            ['name' => 'SKRIN KOYAK', 'report_type_id' => 18],
            ['name' => 'SKRIN TERJATUH', 'report_type_id' => 18],
            ['name' => 'SKRIN MULTIMEDIA TIADA GAMBAR', 'report_type_id' => 18],
            ['name' => 'GAMBAR MULTIMEDIA SENGET', 'report_type_id' => 18],
            ['name' => 'WARNA MULTIMEDIA BERUBAH', 'report_type_id' => 18],
            ['name' => 'LAIN-LAIN ADUAN SISTEM AUDIO VISUAL', 'report_type_id' => 18],
            //Infrastruktur
            ['name' => 'CAT JALAN PUDAR', 'report_type_id' => 19],
            ['name' => 'BAHU JALAN ROSAK', 'report_type_id' => 19],
            ['name' => 'PEMBAHAGI JALAN ROSAK/PECAH', 'report_type_id' => 19],
            ['name' => 'JALAN/PARKIR BERLUBANG', 'report_type_id' => 19],
            ['name' => 'JALAN/PARKIR MENDAP', 'report_type_id' => 19],
            ['name' => 'DINDING PENAHAN PECAH', 'report_type_id' => 19],
            ['name' => 'WAKAF ROSAK', 'report_type_id' => 19],
            ['name' => 'PAGOLA ROSAK', 'report_type_id' => 19],
            ['name' => 'BATU INTERLOCKING MENDAP', 'report_type_id' => 19],
            ['name' => 'TAPAK SUSUR TANGGA PECAH', 'report_type_id' => 19],
            ['name' => 'SAMBUNGAN SUSUR TANGGA PUTUS', 'report_type_id' => 19],
            ['name' => 'PEMBENTUNG PAIP PECAH', 'report_type_id' => 19],
            ['name' => 'PAGAR ROSAK', 'report_type_id' => 19],
            ['name' => 'LONGKANG PECAH', 'report_type_id' => 19],
            ['name' => 'PENUTUP LONGKANG HILAN/ROSAK', 'report_type_id' => 19],
            ['name' => 'GRATING LONGKANG PUTUS', 'report_type_id' => 19],
            ['name' => 'TANAH RUNTUH', 'report_type_id' => 19],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN INFRASTRUKTUR', 'report_type_id' => 19],
            //Perkakasan/Perisian
            ['name' => 'PERISIAN TIDAK BOLEH DIBUKA', 'report_type_id' => 20],
            ['name' => 'KOMPUTER LAMBAT', 'report_type_id' => 20],
            ['name' => 'PRINTER ROSAK', 'report_type_id' => 20],
            ['name' => 'KOMPUTER ROSAK', 'report_type_id' => 20],
            ['name' => 'SERANGAN VIRUS', 'report_type_id' => 20],
            ['name' => 'LAIN-LAIN KEROSAKAN PERKAKASAN / PERISIAN', 'report_type_id' => 20],
            //Rangkaian & Capaian Internet
            ['name' => 'NETWORK TIDAK BERFUNGSI', 'report_type_id' => 21],
            ['name' => 'INTERNET TIDAK BERFUNGSI', 'report_type_id' => 21],
            ['name' => 'CAPAIAN SISTEM DALAMAN TIDAK BERFUNGSI', 'report_type_id' => 21],
            ['name' => 'WIRELESS TIDAK BOLEH BERSAMBUNG', 'report_type_id' => 21],
            ['name' => 'ACCESS POINT TIDAK BERFUNGSI', 'report_type_id' => 21],
            ['name' => 'SWITCH / HUB INTERNET ROSAK', 'report_type_id' => 21],
            ['name' => 'SHARING / LINK (PRINTER/FOLDER)', 'report_type_id' => 21],
            ['name' => 'LAIN-LAIN KEROSAKAN RANGKAIAN', 'report_type_id' => 21],
            //Sistem Servis
            ['name' => 'EMAIL', 'report_type_id' => 22],
            ['name' => 'SISTEM SAGA', 'report_type_id' => 22],
            ['name' => 'SISTEM AWAN (CLOUD)', 'report_type_id' => 22],
            //Sistem Operasi (OS)
            ['name' => 'TIDAK DAPAT MASUK WINDOWS', 'report_type_id' => 23],
            ['name' => 'LAIN-LAIN KEROSAKAN SISTEM OPERASI (OS)', 'report_type_id' => 23],
            //Aplikasi Sistem
            ['name' => 'SISTEM PERSYS', 'report_type_id' => 24],
            ['name' => 'SISTEM SPA', 'report_type_id' => 24],
            ['name' => 'SISTEM SPD', 'report_type_id' => 24],
            ['name' => 'MEDIABANK', 'report_type_id' => 24],
            ['name' => 'SISTEM LATIHAN', 'report_type_id' => 24],
            ['name' => 'SISTEM DDMS', 'report_type_id' => 24],
            ['name' => 'SISTEM MYBAYAR', 'report_type_id' => 24],
            //Perkhidmatan Lanskap
            ['name' => 'LALUAN PEJALAN KAKI, DATARAN TIDAK DIBERSIHKAN', 'report_type_id' => 25],
            ['name' => 'JALANRAYA/PARKING KENDERAAN TIDAK DISAPU', 'report_type_id' => 25],
            ['name' => 'JALAN BERPASIR/BERMINYAK', 'report_type_id' => 25],
            ['name' => 'LONGKANG TIDAK DIBERSIHKAN', 'report_type_id' => 25],
            ['name' => 'SAMPAH LUAR BANGUNAN BERSEPAH', 'report_type_id' => 25],
            ['name' => 'TONG SAMPAH KAWASAN LUAR BANGUNAN MELIMPAH', 'report_type_id' => 25],
            ['name' => 'BUNGKUSAN SAMPAH DAUN TIDAK DIPUNGUT', 'report_type_id' => 25],
            ['name' => 'SCUPPER DRAIN TERSUMBAT/SAMPAH TIDAK DIBERSIHKAN', 'report_type_id' => 25],
            ['name' => 'DAHAN POKOK MELEMPAI KE STRUKTUR', 'report_type_id' => 25],
            ['name' => 'RUMPUT PANJANG/TIDAK DIPOTONG', 'report_type_id' => 25],
            ['name' => 'POKOK MATI / LAYU', 'report_type_id' => 25],
            ['name' => 'DAHAN POKOK PATAH', 'report_type_id' => 25],
            ['name' => 'POKOK TUMBANG', 'report_type_id' => 25],
            ['name' => 'AIR PANCUT TIDAK BERFUNGSI', 'report_type_id' => 25],
            ['name' => 'KOLAM TIDAK DIBERSIHKAN', 'report_type_id' => 25],
            ['name' => 'PAGAR TIDAK DIBERSIHKAN', 'report_type_id' => 25],
            ['name' => 'KEMUDAHAN AWAM (KERUSI & MEJA TAMAN, WAKAF, PAPANTADA)', 'report_type_id' => 25],
            ['name' => 'LAIN-LAIN ADUAN LANSKAP', 'report_type_id' => 25],
            //Peralatan Pejabat
            ['name' => 'KERUSI PEJABAT', 'report_type_id' => 26],
            ['name' => 'KERUSI BANGQUET', 'report_type_id' => 26],
            ['name' => 'MEJA KOMPUTER', 'report_type_id' => 26],
            ['name' => 'MEJA BANGQUET', 'report_type_id' => 26],
            ['name' => 'MEJA MESYUARAT', 'report_type_id' => 26],
            ['name' => 'ALMARI / KABINET / RAK', 'report_type_id' => 26],
            ['name' => 'PARTITION / WORKSTATION', 'report_type_id' => 26],
            ['name' => 'PETI SIMPANAN', 'report_type_id' => 26],
            ['name' => 'WHITEBOARD', 'report_type_id' => 26],
            ['name' => 'TROLI BANGQUET', 'report_type_id' => 26],
            ['name' => 'LAIN-LAIN ADUAN PERALATAN PEJABAT', 'report_type_id' => 26],
            //Telefon
            ['name' => 'TELEFON TIADA BUNYI', 'report_type_id' => 27],
            ['name' => 'GANGGANG TELEFON ROSAK', 'report_type_id' => 27],
            ['name' => 'TELEFON TIDAK BOLEH MENERIMA PANGGILAN', 'report_type_id' => 27],
            ['name' => 'TELEFON TIDAK DAPAT MEMBUAT PANGGILAN', 'report_type_id' => 27],
            ['name' => 'TELEFON TIDAK BERFUNGSI', 'report_type_id' => 27],
            ['name' => 'SOKET TELEFON ROSAK', 'report_type_id' => 27],
            ['name' => 'BUTANG TELEFON  ROSAK', 'report_type_id' => 27],
            ['name' => 'FAKS ROSAK', 'report_type_id' => 27],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN TELEFON', 'report_type_id' => 27],
            //Door Access
            ['name' => 'DOOR ACCESS TIDAK BERFUNGSI', 'report_type_id' => 28],
            ['name' => 'DOOR ACCESS PECAH', 'report_type_id' => 28],
            ['name' => 'DOOR ACCESS TANGGAL', 'report_type_id' => 28],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN DOOR ACCESS', 'report_type_id' => 28],
            //CCTV
            ['name' => 'CCTV TIDAK MEREKOD DATA', 'report_type_id' => 29],
            ['name' => 'CCTV TIADA BERGAMBAR', 'report_type_id' => 29],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN CCTV', 'report_type_id' => 29],
            //Walkie Talkie
            ['name' => 'WALKIE TALKIE TIADA BUNYI', 'report_type_id' => 30],
            ['name' => 'WALKIE TALKIE BERBUNYI BISING', 'report_type_id' => 30],
            ['name' => 'LAIN-LAIN ADUAN KEROSAKAN WALKIE TALKIE', 'report_type_id' => 30],
        ]);
    }
}
